### ISSUE TITLE
Returning invalid chanracters

### ISSUE THREAD

**Issue by amitshinde14** [sidimansourjs/applepay-token#1]
HI buddy,

Could you pls help me to use it properly. I am getting invalid characters after decrypt.

is this solution currently working.

amitshinde14@gmail.com  pls reply me.

your help would be appreciated.

Thanks

**Comment by murcialito** [comment]
Hi,

The solution works fine in nodejs versions +4. 

If you get invalid chars after decrypt it is probably due to bad certificate or invalid test token.

Cheers
