### ISSUE TITLE
What is the 'merchantPrivateKey'?

### ISSUE THREAD

**Issue by SunGg12138** [sidimansourjs/applepay-token#3]
First of all, thank you very much for sharing, but I still have some questions！

![8d5eeaa4-70c6-49cd-adf2-d1e668daf00b](https://user-images.githubusercontent.com/16427275/31802941-be4164c0-b505-11e7-8d6a-6d4b9b55c60b.png)

Is this the one?

**Comment by murcialito** [comment]
added to README
